server:
  port: 9000

spring:
  application:
    name: windcraft-backend-api-gateway-9000
  cloud:
    #GateWay
    gateway:
      # 全局的跨域处理
      globalcors:
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]': # 哪些访问地址做跨域处理
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8081"
              - "http://localhost:8080"
              - "http://127.0.0.1:8081"
              - "http://127.0.0.1:8080"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000  # 这次跨域检测的有效期
      routes:
        #用户模块route
        - id: user-signin
          uri: http://localhost:3001
          predicates:
            - Path=/usersignin/**
            - Method=GET,POST
        #banCRUD模块route
        - id: ban-crud
          uri: http://localhost:2000
          predicates:
            - Path=/bancrud/**
            - Method=GET,POST
        #report-game模块route
        - id: report-game
          uri: http://localhost:5000
          predicates:
            - Path=/reportgame/**
            - Method=GET,POST
        #audit-report-game模块route
        - id: audit-report-game
          uri: http://localhost:1100
          predicates:
            - Path=/auditreportgame/**
            - Method=GET,POST
        #op-crud模块route
        - id: op-crud
          uri: http://localhost:8002
          predicates:
            - Path=/opcrud/**
            - Method=GET,POST
        #user-config模块route
        - id: user-config
          uri: http://localhost:3000
          predicates:
            - Path=/userconfig/**
            - Method=GET,POST
        #user-config-append-user-cover模块route
        - id: user-config-append-user-cover
          uri: http://localhost:3002
          predicates:
            - Path=/userconfigappendusercover/**
            - Method=GET,POST
        #massge-comments模块route
        - id: massge-comments
          uri: http://localhost:6001
          predicates:
            - Path=/massgecomments/**
            - Method=GET,POST
    nacos:
      config:
        server-addr: 127.0.0.1:8848
