server:
  port: 3002

spring:
  data:
    # mongodb
    mongodb:
      uri: mongodb://127.0.0.1:27017/userCoverPicture
  application:
    name: user-config-append-user-cover
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848