server:
  port: 3000

spring:
  servlet:
    # 文件上传限制
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    # mongodb
    mongodb:
      uri: mongodb://127.0.0.1:27017/userHeadPicture
  application:
    name: user-config
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848